=== sinch2147257/cat1/CHC.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid Studio 2021 (https://www.liquid-technologies.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="company">
        <xs:complexType >
            <xs:sequence>
                <xs:element name="Employee" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Emp_name" type="xs:string"></xs:element>
                            <xs:element name="Emp_age" type="xs:integer"></xs:element>
                            <xs:element name="Emp_salary" type="xs:integer"></xs:element>
                            <xs:element name="Emp_emailid" type="xs:string"></xs:element>
                            <xs:element name="Emp_Phonenum" type="xs:integer"></xs:element>
                            <xs:element name="Emp_designation" type="xs:string"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Salary">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:minInclusive value="50000"/>
                <xs:maxInclusive value="200000"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
</xs:schema>

=== sinch2147257/cat1/employee.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="CH.xsl"?>
<company  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="CHC.xsd"
>
        <Employee >
            <Emp_name> Sinchana </Emp_name>
            <Emp_age>25</Emp_age>
            <Emp_salary>60000</Emp_salary>
            <Emp_emailid>sinch@gmail.com</Emp_emailid>
            <Emp_Phonenum>1234567893</Emp_Phonenum>
            <Emp_designation> Trainee </Emp_designation>
        </Employee>

        <Employee >
            <Emp_name> Aneeta </Emp_name>
            <Emp_age>26</Emp_age>
            <Emp_salary>75000</Emp_salary>
            <Emp_emailid>anee@gmail.com</Emp_emailid>
            <Emp_Phonenum>1344567893</Emp_Phonenum>
            <Emp_designation> Trainee </Emp_designation>
        </Employee>

        <Employee >
            <Emp_name> Aami </Emp_name>
            <Emp_age>27</Emp_age>
            <Emp_salary>64000</Emp_salary>
            <Emp_emailid>aami@gmail.com</Emp_emailid>
            <Emp_Phonenum>1234999893</Emp_Phonenum>
            <Emp_designation> software engineer </Emp_designation>
        </Employee>

        <Employee >
            <Emp_name> Arjun</Emp_name>
            <Emp_age>43</Emp_age>
            <Emp_salary>67000</Emp_salary>
            <Emp_emailid>arj@gmail.com</Emp_emailid>
            <Emp_Phonenum>1232348893</Emp_Phonenum>
            <Emp_designation> sales </Emp_designation>
        </Employee>

        <Employee >
            <Emp_name> Sain</Emp_name>
            <Emp_age>48</Emp_age>
            <Emp_salary>68000</Emp_salary>
            <Emp_emailid>sain@gmail.com</Emp_emailid>
            <Emp_Phonenum>9992348893</Emp_Phonenum>
            <Emp_designation> Sales </Emp_designation>
        </Employee>

        <Employee >
            <Emp_name> Ashwin</Emp_name>
            <Emp_age>56</Emp_age>
            <Emp_salary>80000</Emp_salary>
            <Emp_emailid>sain@gmail.com</Emp_emailid>
            <Emp_Phonenum>9992348893</Emp_Phonenum>
            <Emp_designation> Team Lead </Emp_designation>
        </Employee>
</company>
